//==================================================
//     Outputs that match the input variables
//==================================================
output "package" {
  description = "The value of the `package` input variable."
  value       = local.var_package
}
output "package_version" {
  description = "The value of the `package_version` input variable."
  value       = local.var_package_version
}
output "runtime" {
  description = "The value of the `runtime` input variable."
  value       = local.var_runtime
}
output "architecture" {
  description = "The value of the `architecture` input variable."
  value       = local.var_architecture
}
output "region" {
  description = "The value of the `region` input variable."
  value       = local.var_region
}

//==================================================
//       Outputs generated by this module
//==================================================
output "description" {
  description = "The description of the layer."
  value       = local.metadata.description
}
output "license_info" {
  description = "The license info associated with the layer."
  value       = local.metadata.license_info
}
output "compatible_runtimes" {
  description = "A list of runtimes the layer is compatible with."
  value = [
    local.var_runtime
  ]
}
output "compatible_architectures" {
  description = "A list of architectures the layer is compatible with."
  value = [
    local.var_architecture
  ]
}
output "arn" {
  description = "The ARN of the layer, including the most recent layer version number."
  value       = local.metadata.layer_version_arn
}
output "layer_arn" {
  description = "The ARN of the layer, not including any version number."
  value       = local.metadata.layer_arn
}
output "layer_version" {
  description = "The most recent version of the layer."
  value       = local.metadata.layer_version
}
output "created_data" {
  description = "The date this layer was created."
  value       = local.metadata.created_date
}
output "signing_job_arn" {
  description = "The ARN of the signing job that signed this layer."
  value       = local.metadata.signing_job_arn
}
output "signing_profile_version_arn" {
  description = "The ARN of the signing profile that signed this layer."
  value       = local.metadata.signing_profile_version_arn
}
output "source_code_hash" {
  description = "The base64-encoded SHA-256 sum of the layer zip file."
  value       = local.metadata.source_code_hash
}
output "source_code_size" {
  description = "The size, in bytes, of the layer zip file."
  value       = local.metadata.source_code_size
}
